Feat: readable dates
bcgov/cas-ciip-portal pull request #1103
Opened 2020-09-09 18:37 UTC by dleard

- Change UTC format dates to readable format

2020-09-10 01:31 UTC, kriscooke reviewed
I think we should put off a decision on this until Raj returns next week (see comment in [GGIRCS-1620](https://youtrack.button.is/issue/GGIRCS-1620)

2020-09-11 23:23 UTC, matthieu-foucault requested changes
Can we have a single file with `dateFormat` and `dateTimeFormat` functions in it? 
This is the best way to ensure consistency across the application, instead of copy/pasting the time zone and format strings.
`moment.tz` probably shouldn't be used directly by other files unless there's some date comparison needed (e.g in `ReportingYearTable` or `KeyDates`)

2020-09-14 16:12 UTC, kriscooke commented
Agreed, and in that file we may need a couple of possible date formats (eg: date only, date with timestamp etc.)

2020-09-16 22:40 UTC, dleard commented
@kriscooke @matthieu-foucault I removed the moment imports and TIME_ZONE/DATE_FORMAT variables from all files but AltDateInput.tsx & replaced them with calls to the functions in formatDates.ts

2020-09-17 00:49 UTC, kriscooke commented on app/functions/formatDates.ts
> +  database_timestamp: 'YYYY-MM-DDTHH:mm:ss'
It doesn't look like `database_timestamp` and `hours` formats are currently used anywhere - maybe we should just start with the minimum required number of formats and add any others as they become necessary?

2020-09-17 17:23 UTC, kriscooke approved these changes

2020-09-17 19:04 UTC, merged