Allow editing of the last application close date, even if past
bcgov/cas-ciip-portal pull request #1289
Opened 2020-11-18 16:15 UTC by kriscooke

[GGIRCS-2022](https://youtrack.button.is/issue/GGIRCS-2022)

2020-11-24 18:43 UTC, kriscooke commented on app/containers/Admin/ReportingYear/ReportingYearTable.tsx
> +          style={{marginTop: '-330px'}}
@pbastia Unfortunately I realized too late that we'd have to do some gymnastics to try to use your new [`titleControls` button](https://github.com/bcgov/cas-ciip-portal/pull/1290/files#diff-f6385c6dabb76b0f2eb0463c90bf2433c347a773f6167522cf6ebf99ae1e8e74R108) in DefaultLayout with the reporting years admin page - the action needed for the button is known only within the scope of `ReportingYearTable` and isn't available at the top page level... 🤔

2020-11-25 21:18 UTC, matthieu-foucault requested changes

2020-11-25 21:18 UTC, matthieu-foucault commented on app/containers/Admin/ReportingYear/ReportingYearTable.tsx
> +        : 0;
double ternary operators (a quinary operator? :upside_down_face: ) are a bit hard to read. Consider if/else or some other notation for it.

2020-11-25 21:18 UTC, matthieu-foucault commented on app/containers/Admin/ReportingYear/reportingYearValidation.ts
> +  validateExclusiveDateRanges
I would love to see unit tests for all of these functions :)

2020-11-30 17:52 UTC, kriscooke commented on app/containers/Admin/ReportingYear/ReportingYearTable.tsx
> +          style={{marginTop: '-330px'}}
What I've done in the meantime was to tweak the currently implemented absolute positioning of the New Reporting Year button slightly to center it vertically between the title header and the table - there was a problem with using that method to put it in its original place (making it impossible to click on the button).

We need to find a better solution in the component hierarchy for these buttons that do operations on an inner page component (adding items to the SearchTable).

2020-11-30 19:03 UTC, matthieu-foucault approved these changes
Looks good to me

2020-11-30 19:03 UTC, matthieu-foucault commented on app/tests/unit/containers/Admin/ReportingYear/reportingYearValidation.test.ts
> +        applicationOpenTime: TODAY,
I suppose this is fine, as long as we look into mocking the current date before the summer of 2031 :) I really wouldn't bother mocking things now anyway if we're planning on migrating away from Moment.js for our dates

2020-11-30 21:32 UTC, matthieu-foucault approved these changes

2020-11-30 21:32 UTC, merged