feat: advanced validation setup
bcgov/cas-ciip-portal pull request #1571
Opened 2021-03-30 23:34 UTC by dleard

- [x] application_validation_function table
- [x] application_validation_result type
- [x] application_validation function (to iterate on all functions in validation_function table)
- [ ] pgTap tests
- [ ] summary page alert with notifications from each validation where `is_ok` is false
- [ ] unit tests

2021-04-01 20:50 UTC, pbastia submitted a review, later dismissed
Looks great!

2021-04-01 20:50 UTC, pbastia commented on schema/test/unit/computed_columns/application_validation_test.sql
> +    (select count(*) from ggircs_portal.application_validation_function)
This could be hardcoded instead

2021-04-01 21:00 UTC, matthieu-foucault requested changes
Looks great! Just a couple of changes to ensure that tests don't break when we start implementing validation functions

2021-04-01 21:23 UTC, dleard commented on schema/test/unit/computed_columns/application_validation_test.sql
> +insert into ggircs_portal.application_validation_function(validation_function_name, validation_description, validation_failed_message)
`select test_helper.clean_ggircs_portal_schema()` truncates all tables in the schema.

2021-04-01 23:09 UTC, matthieu-foucault commented on schema/test/unit/computed_columns/application_validation_test.sql
> +insert into ggircs_portal.application_validation_function(validation_function_name, validation_description, validation_failed_message)
indeed, didn't notice that!

2021-04-01 23:09 UTC, matthieu-foucault submitted a review, later dismissed

2021-04-01 23:10 UTC, matthieu-foucault commented
@dleard just needs a rebase then

2021-04-02 00:15 UTC, matthieu-foucault approved these changes

2021-04-02 00:15 UTC, merged