Fix: input focus bug
bcgov/cas-ciip-portal pull request #1608
Opened 2021-04-19 21:34 UTC by dleard

- input focus was caused by moving the CUSTOM_FIELDS in Form.tsx inside the function component in an attempt to not rely on formContext. I've undone this change & we can revisit the idea of not using formContext later
- fixed the dev data in formResult.sql, numeric values were quoted. This was causing them to be parsed as strings & throw validation errors
- added a null diffQuery prop to the ApplicationWizardConfirmation file to remove a relay warning
- removed format: naics from the administration form_json as it is unused now that we are using a dropdown. (was throwing a relay warning)
- fixed the dev data in application-2018.sql fixture to not rely on hardcoded application IDs

2021-04-20 19:01 UTC, pbastia requested changes
Just a `console.log` left behind, looks great!

2021-04-20 22:07 UTC, kriscooke reviewed
👌 Thanks, looks to to me!

2021-04-20 22:09 UTC, pbastia submitted a review, later dismissed

2021-04-21 14:42 UTC, matthieu-foucault requested changes

2021-04-21 14:42 UTC, matthieu-foucault commented on schema/data/dev/form_result.sql
> +  ('{"sourceTypes": [{"gases": [{"gwp": 2, "gasType": "CO2nonbio", "annualCO2e": 5, "annualEmission": 6, "gasDescription": "Carbon dioxide from non-biomass"}, {"gwp": 1, "gasType": "CO2", "annualCO2e
same issue L19 above. Those lines should be formatted for better readability

2021-04-21 14:42 UTC, matthieu-foucault commented on schema/data/dev/application-2018.sql
> +      -- Create a legacy application_review_step for the 2018 application with ID=3
just some minor updates needed in the comments (`ID=3`)

2021-04-21 17:59 UTC, matthieu-foucault approved these changes

2021-04-21 17:59 UTC, merged