chore: add sysdig links/monitoring to shipit
bcgov/cas-ciip-portal pull request #1674
Opened 2021-05-12 21:58 UTC by dleard

I think the iframe will have an issue unless we make the dashboard public in sysdig?

2021-05-12 22:16 UTC, matthieu-foucault commented
Let's merge and see what it looks like :smile:

2021-05-13 14:56 UTC, matthieu-foucault commented
![image](https://user-images.githubusercontent.com/2684022/118143929-b5325700-b3c0-11eb-8972-d000a214e0c6.png)

2021-05-13 14:56 UTC, matthieu-foucault commented
See https://cas-shipit.apps.silver.devops.gov.bc.ca/bcgov/cas-ciip-portal/dontdeployme

2021-05-13 14:57 UTC, matthieu-foucault commented
The links don't appear to be showing. I was already logged in sysdig, so the monitoring shows up. We just need to figure out how to make it bigger

2021-05-13 14:59 UTC, matthieu-foucault commented
Nevermind, the links appeared after shipit synchronized. Looks like the PVC usage dashboard wasn't share with all teams though

2021-05-13 15:02 UTC, matthieu-foucault commented
See https://github.com/Shopify/shipit-engine/blob/236ffbfefb55ffc5faaa2ec27f72bb173106b3d4/examples/shipit.yml#L17 to set the iframe width and height

2021-05-13 15:06 UTC, matthieu-foucault commented
I don't think that we need the monitoring to show up in anything else than prod. I'm not sure how the environment-specific yml files are handled though. Maybe try adding a `shipit.dontdeployme.yml`, which only has the monitoring settings, to see if it merges it with the base `shipit.yml`

2021-05-13 16:02 UTC, dleard commented
Cool thanks, I'll play with the iframe & PVC dashboard. Did you create a new shipit stack and just point it to this branch to make the 'dontdeployme'?

2021-05-13 16:09 UTC, matthieu-foucault commented
Yes I created a shipit stack, that was the easiest to test this.

2021-05-14 20:14 UTC, dleard commented
shipit.dontdeployme,yml overrides the default shipit.yml, it does not merge with it.
The iframe has been enlarged but it has some permission / data issues. I set the dashboard to be shared with all teams but if you are not logged into the CIIP namespace's sysdig team the data will show up as `No data` because the other namespaces can't find those pods

2021-05-17 17:24 UTC, dleard commented
@matthieu-foucault Per your question in stand-up today: Yes, you can log in to sysdig from the iframe if you're not already logged in

2021-05-17 20:42 UTC, matthieu-foucault requested changes

2021-05-17 20:42 UTC, matthieu-foucault commented on shipit.dontdeployme.yml
> +    - echo 'Not to be deployed'
Looks good. Let's just copy what's in the default shipit.yml and rename this to `shipit.prod.yml`

2021-05-17 20:42 UTC, matthieu-foucault commented on shipit.dontdeployme.yml
> +  checklist: []
```suggestion
  checklist:
    - Is today not Friday?
```

2021-05-17 20:55 UTC, matthieu-foucault requested changes

2021-05-17 20:55 UTC, matthieu-foucault commented on shipit.prod.yml
> +  hide:
```suggestion
  require:
```
the release approval is actually required for prod (and test)

2021-05-17 20:59 UTC, matthieu-foucault approved these changes

2021-05-17 21:21 UTC, merged