BugFix: clicking on the icon sends the right status
bcgov/cas-ciip-portal pull request #1790
Opened 2021-06-22 22:45 UTC by pbastia

fix for issue where clicking on the icon (not the button around) would trigger a `null` status for the application in the database

![image](https://user-images.githubusercontent.com/11507754/123009074-e5cac080-d370-11eb-9c0f-ac9cec595dd8.png)

2021-06-22 22:50 UTC, naomiaro approved these changes

2021-06-22 22:51 UTC, matthieu-foucault commented on app/components/Admin/ApplicationReview/DecisionModal.tsx
>              value="REQUESTED_CHANGES"
Are the values needed?

2021-06-22 22:51 UTC, naomiaro commented on app/components/Admin/ApplicationReview/DecisionModal.tsx
>            value="REJECTED"
maybe don't need these values anymore

2021-06-22 22:53 UTC, naomiaro requested changes
Didn't notice the buttons still had values until the end woops

2021-06-22 22:57 UTC, naomiaro submitted a review, later dismissed

2021-06-22 23:53 UTC, matthieu-foucault approved these changes

2021-06-23 00:04 UTC, matthieu-foucault approved these changes

2021-06-23 00:41 UTC, merged