chore: fix CVE-2021-23343
bcgov/cas-ciip-portal pull request #1956
Opened 2021-08-12 16:33 UTC by dleard

2021-08-12 17:01 UTC, pbastia commented on app/yarn.lock
>    version "1.0.6"
I think you meant to change the second "1.0.6" instead

2021-08-13 16:17 UTC, pbastia requested changes
just a tiny yarn comment, looks great otherwise!

2021-08-13 16:17 UTC, pbastia commented on app/yarn.lock
>    integrity sha512-GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==
Just need to remove those 2 lines and re-run yarn install

2021-08-13 16:36 UTC, dleard commented
closes #1955

2021-08-13 16:44 UTC, pbastia approved these changes
:shipit: 👌

2021-08-13 17:37 UTC, merged