Fix: show submit button
bcgov/cas-ciip-portal pull request #1991
Opened 2021-09-27 20:06 UTC by dleard

Submit button was hidden for all older applications. Should have only been hidden for older applications with version <= 1

2021-09-27 20:49 UTC, pbastia requested changes
just the comment, looks great otherwise!

2021-09-27 20:49 UTC, pbastia commented on app/containers/Applications/ApplicationWizardConfirmation.tsx
>    // Ensure the application being submitted is from the correct reporting year (ie: not a previous year)
```suggestion
// Ensure the application being submitted is either for the correct reporting year (i.e. not a previous year), or a version greater than 1 (i.e. an existing application being re-submitted)

2021-09-27 21:06 UTC, pbastia approved these changes

2021-09-27 21:24 UTC, merged

2021-10-06 20:17 UTC, matthieu-foucault commented on app/containers/Applications/ApplicationWizardConfirmation.tsx
> +    applicationRevision.versionNumber > 1;
https://bcgov-cas.promyze.app/#/CAS%20GGIRCS/home?practiceId=615c7dc0fbe2630fad4024ef